### ISSUE TITLE
Doesn't work on Chrome (malformed constraints object)

### ISSUE THREAD

**Issue by wamoyo** [wamoyo/webrtc-cafe#1]
Here's the error we're getting: `Uncaught TypeError: Failed to execute 'createAnswer' on 'RTCPeerConnection': Malformed constraints object.  (index):220 (anonymous function)`

And here's the relevant code: 

```
var remoteSessionDescription = new RTCSessionDescription(data.offer);
pc.setRemoteDescription(remoteSessionDescription, function() {
  pc.createAnswer( function (answer) { // **This is line 220**
    var localSessionDescription = new RTCSessionDescription(answer);
    pc.setLocalDescription(localSessionDescription, function () {
    // ...
  }, fail, { offerToReceiveAudio: true, offerToReceiveVideo: true }); //**constraints**
}, fail); // Handle error.
```

**Comment by nagarjun-ananth** [comment]
var mediaConstraints = {  
  "mandatory": {
    "OfferToReceiveAudio":true, 
    "OfferToReceiveVideo":true
  }
};
you could use this structure. The O is caps in the new spec

**Comment by wamoyo** [comment]
Thanks, @nagarjun-ananth. Do you know if this is where the spec has landed? Or are things still settling down?
